# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3fd938a5e0de6ac9bc1070ce093232bd"
application_url = "https://skins-keyboard-compare-vision.trycloudflare.com"
embedded = true
name = "QrcodeApp"
handle = "qrcodeapp-32"

[build]
include_config_on_deploy = true
dev_store_url = "ali-myfirststore.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://skins-keyboard-compare-vision.trycloudflare.com/auth/callback",
  "https://skins-keyboard-compare-vision.trycloudflare.com/auth/shopify/callback",
  "https://skins-keyboard-compare-vision.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
